import type {
  Album,
  AppNotification,
  Chat,
  ChatMessage,
  Family,
  FamilyEvent,
  ForumCategory,
  ForumThread,
  MediaItem,
  Memory,
  Recipe,
  TreeRelationship,
  User,
  VaultItem,
} from "./types";

const u = (seed: string) => `https://api.dicebear.com/9.x/personas/svg?seed=${seed}`;

const P = (id: string, w = 1200) => `https://images.unsplash.com/photo-${id}?w=${w}&q=80&auto=format&fit=crop`;

/** Curated Unsplash photo ids: families, gatherings, elders, children, nature. */
export const photoPool = [
  "1511895426328-dc8714191300",
  "1478061653917-455ba7f4a541",
  "1543269865-cbf427effbad",
  "1529156069898-49953e39b3ac",
  "1414235077428-338989a2e8c0",
  "1516627145497-ae6968895b74",
  "1470229722913-7ea0d7a3c8b4",
  "1520854221256-17451cc331bf",
  "1519741497674-611481863552",
  "1522673607200-164d1b6ce486",
  "1447752875215-b2761acb3c5d",
  "1441974231531-c6227db76b6e",
  "1476611317561-60117649dd94",
  "1490730141103-6cac27aaab94",
  "1504198453319-5ce911bafcde",
  "1509099836639-18ba1795216d",
  "1517849845537-4d257902454a",
  "1503023345310-bd7c1de61c7d",
  "1499750310107-5fef28a66643",
  "1464349095431-e9a21285b5f3",
  "1500530855697-b586d89ba3ee",
  "1506126613408-eca07ce68773",
  "1493millis",
].filter((id) => !id.includes("millis"));

export const photo = P;

export const families: Family[] = [
  {
    id: "fam_johnson",
    name: "The Johnson Family",
    slug: "johnson-family",
    founderName: "Robert Johnson Sr.",
    foundedYear: 1948,
    coverPhotoUrl: P("1511895426328-dc8714191300", 1600),
    description: "Four generations, one table. Toronto since 1948.",
    subscription: "founder",
    storageUsedGB: 38.4,
    storageQuotaGB: 250,
  },
  {
    id: "fam_chen",
    name: "The Chen Family",
    slug: "chen-family",
    founderName: "Wei Chen",
    foundedYear: 1965,
    coverPhotoUrl: P("1470229722913-7ea0d7a3c8b4", 1600),
    description: "From Guangzhou to Vancouver — recipes, letters, and long walks.",
    subscription: "standard",
    storageUsedGB: 6.2,
    storageQuotaGB: 50,
  },
];

export const users: User[] = [
  {
    id: "u_robert",
    familyId: "fam_johnson",
    email: "robert.johnson@memorial.eternal-memories.io",
    firstName: "Robert",
    lastName: "Johnson",
    displayName: "Robert Johnson Sr.",
    avatarUrl: u("robert-johnson-1925"),
    coverPhotoUrl: P("1441974231531-c6227db76b6e", 1600),
    bio: "Patriarch of the Johnson family. WWII veteran, carpenter, gardener. Built the cottage at Lake Simcoe with his own hands.",
    birthDate: "1925-03-14",
    deathDate: "2003-11-22",
    status: "deceased",
    location: "Toronto, ON",
    role: "elder",
    generation: 1,
    relationshipToViewer: "Great-Grandfather",
    lifeTimeline: [
      { id: "le1", year: 1925, title: "Born in Toronto, Ontario" },
      { id: "le2", year: 1943, title: "Enlisted in the Canadian Army" },
      { id: "le3", year: 1948, title: "Married Helen Wright" },
      { id: "le4", year: 1950, title: "Founded Johnson Carpentry Co." },
      { id: "le5", year: 1961, title: "Built the cottage at Lake Simcoe" },
      { id: "le6", year: 2003, title: "Passed peacefully, surrounded by family" },
    ],
    stats: { memoriesShared: 0, photosUploaded: 0, vaultItems: 3, children: 3 },
  },
  {
    id: "u_helen",
    familyId: "fam_johnson",
    email: "helen.johnson@memorial.eternal-memories.io",
    firstName: "Helen",
    lastName: "Johnson",
    displayName: "Helen Johnson (née Wright)",
    avatarUrl: u("helen-wright-1928"),
    coverPhotoUrl: P("1500530855697-b586d89ba3ee", 1600),
    bio: "Matriarch. Grade-three teacher for forty years, storyteller extraordinaire, keeper of every recipe card in this archive.",
    birthDate: "1928-07-02",
    deathDate: "2018-04-10",
    status: "deceased",
    location: "Toronto, ON",
    role: "elder",
    generation: 1,
    relationshipToViewer: "Great-Grandmother",
    lifeTimeline: [
      { id: "le7", year: 1928, title: "Born in Halifax, Nova Scotia" },
      { id: "le8", year: 1949, title: "Began teaching at Withrow Public School" },
      { id: "le9", year: 1955, title: "Daughter Margaret born" },
      { id: "le10", year: 1989, title: "Retired after 40 years of teaching" },
      { id: "le11", year: 2016, title: "Recorded 14 hours of family stories" },
      { id: "le12", year: 2018, title: "Passed at home in the spring" },
    ],
    stats: { memoriesShared: 6, photosUploaded: 41, vaultItems: 4, children: 3 },
  },
  {
    id: "u_margaret",
    familyId: "fam_johnson",
    email: "margaret.thompson@eternal-memories.io",
    firstName: "Margaret",
    lastName: "Thompson",
    displayName: "Margaret Johnson-Thompson",
    avatarUrl: u("margaret-johnson-1955"),
    coverPhotoUrl: P("1476611317561-60117649dd94", 1600),
    bio: "Retired nurse, relentless organiser of reunions, the reason this archive exists at all.",
    birthDate: "1955-05-19",
    status: "living",
    location: "Toronto, ON",
    role: "moderator",
    generation: 2,
    relationshipToViewer: "Mother",
    lifeTimeline: [
      { id: "le13", year: 1955, title: "Born in Toronto" },
      { id: "le14", year: 1977, title: "Graduated nursing, Toronto General" },
      { id: "le15", year: 1979, title: "Married Peter Thompson" },
      { id: "le16", year: 1980, title: "Son John born" },
      { id: "le17", year: 2019, title: "Retired after 42 years of nursing" },
    ],
    stats: { memoriesShared: 87, photosUploaded: 312, vaultItems: 5, children: 2 },
  },
  {
    id: "u_peter",
    familyId: "fam_johnson",
    email: "peter.thompson@eternal-memories.io",
    firstName: "Peter",
    lastName: "Thompson",
    displayName: "Peter Thompson",
    avatarUrl: u("peter-thompson-1952"),
    coverPhotoUrl: P("1464349095431-e9a21285b5f3", 1600),
    bio: "Retired railway engineer. Believes every problem is solvable with patience and a good thermos.",
    birthDate: "1952-01-08",
    status: "living",
    location: "Toronto, ON",
    role: "member",
    generation: 2,
    relationshipToViewer: "Father",
    lifeTimeline: [
      { id: "le18", year: 1952, title: "Born in Winnipeg, Manitoba" },
      { id: "le19", year: 1979, title: "Married Margaret Johnson" },
      { id: "le20", year: 2017, title: "Retired from Canadian National Railway" },
    ],
    stats: { memoriesShared: 24, photosUploaded: 96, vaultItems: 2, children: 2 },
  },
  {
    id: "u_david",
    familyId: "fam_johnson",
    email: "david.johnson@eternal-memories.io",
    firstName: "David",
    lastName: "Johnson",
    displayName: "David Johnson",
    avatarUrl: u("david-johnson-1958"),
    coverPhotoUrl: P("1506126613408-eca07ce68773", 1600),
    bio: "Took over Johnson Carpentry in 1991. Still uses his father's hand plane every single week.",
    birthDate: "1958-09-30",
    status: "living",
    location: "Barrie, ON",
    role: "member",
    generation: 2,
    relationshipToViewer: "Uncle",
    lifeTimeline: [
      { id: "le21", year: 1958, title: "Born in Toronto" },
      { id: "le22", year: 1991, title: "Took over Johnson Carpentry Co." },
      { id: "le23", year: 1984, title: "Married Susan Alvarez" },
    ],
    stats: { memoriesShared: 41, photosUploaded: 140, vaultItems: 1, children: 2 },
  },
  {
    id: "u_susan",
    familyId: "fam_johnson",
    email: "susan.johnson@eternal-memories.io",
    firstName: "Susan",
    lastName: "Johnson",
    displayName: "Susan Johnson (née Alvarez)",
    avatarUrl: u("susan-alvarez-1961"),
    coverPhotoUrl: P("1490730141103-6cac27aaab94", 1600),
    bio: "Painter, gardener, and the family's unofficial archivist of birthday cards.",
    birthDate: "1961-02-11",
    status: "living",
    location: "Barrie, ON",
    role: "member",
    generation: 2,
    relationshipToViewer: "Aunt",
    lifeTimeline: [
      { id: "le24", year: 1961, title: "Born in Madrid, Spain" },
      { id: "le25", year: 1984, title: "Married David Johnson" },
      { id: "le26", year: 2005, title: "First solo exhibition in Barrie" },
    ],
    stats: { memoriesShared: 63, photosUploaded: 201, vaultItems: 2, children: 2 },
  },
  {
    id: "u_john",
    familyId: "fam_johnson",
    email: "john.thompson@eternal-memories.io",
    firstName: "John",
    lastName: "Thompson",
    displayName: "John Thompson",
    avatarUrl: u("john-thompson-1980"),
    coverPhotoUrl: P("1519741497674-611481863552", 1600),
    bio: "Family admin. Started this archive after Grandma Helen passed, so nothing else would slip away.",
    birthDate: "1980-06-24",
    status: "living",
    location: "Toronto, ON",
    role: "family_admin",
    generation: 3,
    relationshipToViewer: "You",
    lifeTimeline: [
      { id: "le27", year: 1980, title: "Born in Toronto" },
      { id: "le28", year: 2006, title: "Married Emily Carter" },
      { id: "le29", year: 2010, title: "Daughter Olivia born" },
      { id: "le30", year: 2013, title: "Son Noah born" },
      { id: "le31", year: 2018, title: "Founded the Eternal — Memories family archive" },
    ],
    stats: { memoriesShared: 132, photosUploaded: 508, vaultItems: 6, children: 2 },
  },
  {
    id: "u_emily",
    familyId: "fam_johnson",
    email: "emily.thompson@eternal-memories.io",
    firstName: "Emily",
    lastName: "Thompson",
    displayName: "Emily Thompson (née Carter)",
    avatarUrl: u("emily-carter-1982"),
    coverPhotoUrl: P("1504198453319-5ce911bafcde", 1600),
    bio: "Photographer. Responsible for roughly half the pictures in this gallery.",
    birthDate: "1982-11-03",
    status: "living",
    location: "Toronto, ON",
    role: "moderator",
    generation: 3,
    relationshipToViewer: "Wife",
    lifeTimeline: [
      { id: "le32", year: 1982, title: "Born in Ottawa" },
      { id: "le33", year: 2006, title: "Married John Thompson" },
      { id: "le34", year: 2014, title: "Opened Carter Studio" },
    ],
    stats: { memoriesShared: 118, photosUploaded: 742, vaultItems: 3, children: 2 },
  },
  {
    id: "u_michael",
    familyId: "fam_johnson",
    email: "michael.johnson@eternal-memories.io",
    firstName: "Michael",
    lastName: "Johnson",
    displayName: "Michael Johnson",
    avatarUrl: u("michael-johnson-1985"),
    coverPhotoUrl: P("1447752875215-b2761acb3c5d", 1600),
    bio: "Marine biologist in Halifax. Calls every Sunday, misses every reunion.",
    birthDate: "1985-08-17",
    status: "living",
    location: "Halifax, NS",
    role: "member",
    generation: 3,
    relationshipToViewer: "Cousin",
    lifeTimeline: [
      { id: "le35", year: 1985, title: "Born in Barrie" },
      { id: "le36", year: 2012, title: "PhD, Dalhousie University" },
      { id: "le37", year: 2021, title: "Led the Bay of Fundy survey" },
    ],
    stats: { memoriesShared: 29, photosUploaded: 87, vaultItems: 1, children: 0 },
  },
  {
    id: "u_rachel",
    familyId: "fam_johnson",
    email: "rachel.lee@eternal-memories.io",
    firstName: "Rachel",
    lastName: "Johnson-Lee",
    displayName: "Rachel Johnson-Lee",
    avatarUrl: u("rachel-johnson-1988"),
    coverPhotoUrl: P("1522673607200-164d1b6ce486", 1600),
    bio: "Genealogy obsessive. Has traced the Wright line back to 1790 and will tell you about it.",
    birthDate: "1988-04-06",
    status: "living",
    location: "Montréal, QC",
    role: "moderator",
    generation: 3,
    relationshipToViewer: "Cousin",
    lifeTimeline: [
      { id: "le38", year: 1988, title: "Born in Barrie" },
      { id: "le39", year: 2015, title: "Married Daniel Lee" },
      { id: "le40", year: 2016, title: "Daughter Ava born" },
      { id: "le41", year: 2023, title: "Traced the Wright line to 1790" },
    ],
    stats: { memoriesShared: 74, photosUploaded: 163, vaultItems: 2, children: 1 },
  },
  {
    id: "u_olivia",
    familyId: "fam_johnson",
    email: "olivia.thompson@eternal-memories.io",
    firstName: "Olivia",
    lastName: "Thompson",
    displayName: "Olivia Thompson",
    avatarUrl: u("olivia-thompson-2010"),
    coverPhotoUrl: P("1499750310107-5fef28a66643", 1600),
    bio: "Fifteen. Plays cello, films everything, curates the 'Cottage Chaos' album.",
    birthDate: "2010-09-12",
    status: "living",
    location: "Toronto, ON",
    role: "youth",
    generation: 4,
    relationshipToViewer: "Daughter",
    lifeTimeline: [
      { id: "le42", year: 2010, title: "Born in Toronto" },
      { id: "le43", year: 2022, title: "First cello recital" },
    ],
    stats: { memoriesShared: 46, photosUploaded: 214, vaultItems: 1, children: 0 },
  },
  {
    id: "u_noah",
    familyId: "fam_johnson",
    email: "noah.thompson@eternal-memories.io",
    firstName: "Noah",
    lastName: "Thompson",
    displayName: "Noah Thompson",
    avatarUrl: u("noah-thompson-2013"),
    coverPhotoUrl: P("1509099836639-18ba1795216d", 1600),
    bio: "Twelve. Hockey, dinosaurs, and an encyclopedic memory for great-grandpa's stories.",
    birthDate: "2013-03-28",
    status: "living",
    location: "Toronto, ON",
    role: "youth",
    generation: 4,
    relationshipToViewer: "Son",
    lifeTimeline: [{ id: "le44", year: 2013, title: "Born in Toronto" }],
    stats: { memoriesShared: 12, photosUploaded: 38, vaultItems: 0, children: 0 },
  },
  {
    id: "u_ava",
    familyId: "fam_johnson",
    email: "ava.lee@eternal-memories.io",
    firstName: "Ava",
    lastName: "Lee",
    displayName: "Ava Johnson-Lee",
    avatarUrl: u("ava-lee-2016"),
    coverPhotoUrl: P("1517849845537-4d257902454a", 1600),
    bio: "Nine. Draws the family tree in crayon, which is arguably the better version.",
    birthDate: "2016-12-01",
    status: "living",
    location: "Montréal, QC",
    role: "youth",
    generation: 4,
    relationshipToViewer: "First cousin once removed",
    lifeTimeline: [{ id: "le45", year: 2016, title: "Born in Montréal" }],
    stats: { memoriesShared: 5, photosUploaded: 11, vaultItems: 0, children: 0 },
  },

  // ---- The Chen Family ----
  {
    id: "c_wei",
    familyId: "fam_chen",
    email: "wei.chen@memorial.eternal-memories.io",
    firstName: "Wei",
    lastName: "Chen",
    displayName: "Wei Chen",
    avatarUrl: u("wei-chen-1940"),
    coverPhotoUrl: P("1470229722913-7ea0d7a3c8b4", 1600),
    bio: "Left Guangzhou in 1965 with two suitcases and a recipe book.",
    birthDate: "1940-10-05",
    deathDate: "2015-06-19",
    status: "deceased",
    location: "Vancouver, BC",
    role: "elder",
    generation: 1,
    relationshipToViewer: "Family elder",
    lifeTimeline: [
      { id: "cl1", year: 1940, title: "Born in Guangzhou" },
      { id: "cl2", year: 1965, title: "Emigrated to Vancouver" },
      { id: "cl3", year: 1972, title: "Opened Chen's Kitchen on Main Street" },
    ],
    stats: { memoriesShared: 3, photosUploaded: 22, vaultItems: 2, children: 2 },
  },
  {
    id: "c_lin",
    familyId: "fam_chen",
    email: "lin.chen@eternal-memories.io",
    firstName: "Lin",
    lastName: "Chen",
    displayName: "Lin Chen",
    avatarUrl: u("lin-chen-1944"),
    coverPhotoUrl: P("1441974231531-c6227db76b6e", 1600),
    bio: "Keeper of the family's handwritten recipe book. Eighty-one and still gardening.",
    birthDate: "1944-02-20",
    status: "living",
    location: "Vancouver, BC",
    role: "elder",
    generation: 1,
    relationshipToViewer: "Family elder",
    lifeTimeline: [{ id: "cl4", year: 1944, title: "Born in Guangzhou" }],
    stats: { memoriesShared: 18, photosUploaded: 60, vaultItems: 3, children: 2 },
  },
  {
    id: "c_daniel",
    familyId: "fam_chen",
    email: "daniel.chen@eternal-memories.io",
    firstName: "Daniel",
    lastName: "Chen",
    displayName: "Daniel Chen",
    avatarUrl: u("daniel-chen-1968"),
    coverPhotoUrl: P("1504198453319-5ce911bafcde", 1600),
    bio: "Second-generation restaurateur, first-generation spreadsheet enthusiast.",
    birthDate: "1968-07-14",
    status: "living",
    location: "Vancouver, BC",
    role: "family_admin",
    generation: 2,
    relationshipToViewer: "Family admin",
    lifeTimeline: [{ id: "cl5", year: 1968, title: "Born in Vancouver" }],
    stats: { memoriesShared: 34, photosUploaded: 121, vaultItems: 2, children: 2 },
  },
  {
    id: "c_grace",
    familyId: "fam_chen",
    email: "grace.chen@eternal-memories.io",
    firstName: "Grace",
    lastName: "Chen",
    displayName: "Grace Chen",
    avatarUrl: u("grace-chen-1971"),
    coverPhotoUrl: P("1490730141103-6cac27aaab94", 1600),
    bio: "Paediatrician. Runs the family's Lunar New Year logistics like a field hospital.",
    birthDate: "1971-11-09",
    status: "living",
    location: "Vancouver, BC",
    role: "moderator",
    generation: 2,
    relationshipToViewer: "Family member",
    lifeTimeline: [{ id: "cl6", year: 1971, title: "Born in Hong Kong" }],
    stats: { memoriesShared: 27, photosUploaded: 98, vaultItems: 1, children: 2 },
  },
  {
    id: "c_sophia",
    familyId: "fam_chen",
    email: "sophia.chen@eternal-memories.io",
    firstName: "Sophia",
    lastName: "Chen",
    displayName: "Sophia Chen",
    avatarUrl: u("sophia-chen-1996"),
    coverPhotoUrl: P("1519741497674-611481863552", 1600),
    bio: "Architect in Toronto. Digitised every photo album in the house over one Christmas.",
    birthDate: "1996-03-02",
    status: "living",
    location: "Toronto, ON",
    role: "member",
    generation: 3,
    relationshipToViewer: "Family member",
    lifeTimeline: [{ id: "cl7", year: 1996, title: "Born in Vancouver" }],
    stats: { memoriesShared: 21, photosUploaded: 143, vaultItems: 1, children: 0 },
  },
  {
    id: "c_lucas",
    familyId: "fam_chen",
    email: "lucas.chen@eternal-memories.io",
    firstName: "Lucas",
    lastName: "Chen",
    displayName: "Lucas Chen",
    avatarUrl: u("lucas-chen-1999"),
    coverPhotoUrl: P("1447752875215-b2761acb3c5d", 1600),
    bio: "Sound engineer. Restored 40 hours of grandpa's cassette tapes.",
    birthDate: "1999-05-27",
    status: "living",
    location: "Vancouver, BC",
    role: "member",
    generation: 3,
    relationshipToViewer: "Family member",
    lifeTimeline: [{ id: "cl8", year: 1999, title: "Born in Vancouver" }],
    stats: { memoriesShared: 15, photosUploaded: 44, vaultItems: 2, children: 0 },
  },
  {
    id: "c_mei",
    familyId: "fam_chen",
    email: "mei.chen@eternal-memories.io",
    firstName: "Mei",
    lastName: "Chen",
    displayName: "Mei Chen",
    avatarUrl: u("mei-chen-2001"),
    coverPhotoUrl: P("1499750310107-5fef28a66643", 1600),
    bio: "Medical student. Writes the family newsletter nobody asked for but everyone reads.",
    birthDate: "2001-09-15",
    status: "living",
    location: "Montréal, QC",
    role: "member",
    generation: 3,
    relationshipToViewer: "Family member",
    lifeTimeline: [{ id: "cl9", year: 2001, title: "Born in Vancouver" }],
    stats: { memoriesShared: 12, photosUploaded: 33, vaultItems: 0, children: 0 },
  },
  {
    id: "c_henry",
    familyId: "fam_chen",
    email: "henry.chen@eternal-memories.io",
    firstName: "Henry",
    lastName: "Chen",
    displayName: "Henry Chen",
    avatarUrl: u("henry-chen-2004"),
    coverPhotoUrl: P("1509099836639-18ba1795216d", 1600),
    bio: "Twenty-one, competitive swimmer, unofficial family barista.",
    birthDate: "2004-01-30",
    status: "living",
    location: "Vancouver, BC",
    role: "youth",
    generation: 3,
    relationshipToViewer: "Family member",
    lifeTimeline: [{ id: "cl10", year: 2004, title: "Born in Vancouver" }],
    stats: { memoriesShared: 7, photosUploaded: 25, vaultItems: 0, children: 0 },
  },
];

export const relationships: TreeRelationship[] = [
  { id: "r1", from: "u_robert", to: "u_helen", type: "spouse" },
  { id: "r2", from: "u_robert", to: "u_margaret", type: "parent" },
  { id: "r3", from: "u_helen", to: "u_margaret", type: "parent" },
  { id: "r4", from: "u_robert", to: "u_david", type: "parent" },
  { id: "r5", from: "u_helen", to: "u_david", type: "parent" },
  { id: "r6", from: "u_margaret", to: "u_peter", type: "spouse" },
  { id: "r7", from: "u_david", to: "u_susan", type: "spouse" },
  { id: "r8", from: "u_margaret", to: "u_john", type: "parent" },
  { id: "r9", from: "u_peter", to: "u_john", type: "parent" },
  { id: "r10", from: "u_david", to: "u_michael", type: "parent" },
  { id: "r11", from: "u_susan", to: "u_michael", type: "parent" },
  { id: "r12", from: "u_david", to: "u_rachel", type: "parent" },
  { id: "r13", from: "u_susan", to: "u_rachel", type: "parent" },
  { id: "r14", from: "u_john", to: "u_emily", type: "spouse" },
  { id: "r15", from: "u_john", to: "u_olivia", type: "parent" },
  { id: "r16", from: "u_emily", to: "u_olivia", type: "parent" },
  { id: "r17", from: "u_john", to: "u_noah", type: "parent" },
  { id: "r18", from: "u_emily", to: "u_noah", type: "parent" },
  { id: "r19", from: "u_rachel", to: "u_ava", type: "parent" },
  // Chen
  { id: "r20", from: "c_wei", to: "c_lin", type: "spouse" },
  { id: "r21", from: "c_wei", to: "c_daniel", type: "parent" },
  { id: "r22", from: "c_lin", to: "c_daniel", type: "parent" },
  { id: "r23", from: "c_daniel", to: "c_grace", type: "spouse" },
  { id: "r24", from: "c_daniel", to: "c_sophia", type: "parent" },
  { id: "r25", from: "c_grace", to: "c_sophia", type: "parent" },
  { id: "r26", from: "c_daniel", to: "c_lucas", type: "parent" },
  { id: "r27", from: "c_grace", to: "c_lucas", type: "parent" },
  { id: "r28", from: "c_daniel", to: "c_mei", type: "parent" },
  { id: "r29", from: "c_grace", to: "c_henry", type: "parent" },
];

/* ------------------------------------------------------------------ */
/* Memories                                                            */
/* ------------------------------------------------------------------ */

const DAY = 86_400_000;
const now = Date.UTC(2026, 7, 1, 9, 0, 0);
const ago = (days: number, hours = 0) => new Date(now - days * DAY - hours * 3_600_000).toISOString();

const johnsonAuthors = [
  "u_john",
  "u_emily",
  "u_margaret",
  "u_david",
  "u_susan",
  "u_rachel",
  "u_michael",
  "u_olivia",
  "u_peter",
];

const memoryTexts = [
  "Found this in the bottom of Grandma Helen's sewing box. Nobody has any idea who the woman on the left is — Rachel, this is your department.",
  "Cottage weekend. Noah caught his first pike, then refused to touch it. Some traditions really do run in the family.",
  "Dad would have been 100 today. We made his pancakes, the ones with too much cinnamon, and told the hand-plane story again.",
  "Sunday dinner, 14 people, one table that has now been extended three times since 1961.",
  "Scanned another shoebox of slides tonight. 1974 was apparently entirely orange.",
  "Olivia's cello recital. She played the piece Grandma Helen used to hum in the kitchen and half the row was crying.",
  "The old carpentry sign came down off the shop today. It's in the garage now, and it is absolutely not going anywhere.",
  "Reunion planning has officially begun. Twenty-eight confirmed. Someone please volunteer for the potato salad.",
  "Ava drew the family tree at school. Uncle Michael is a fish. He has been informed.",
  "Grandma's handwriting on the back of this one: 'Lake Simcoe, first summer, the roof leaked.'",
  "Twelve years today since Dad's last Christmas with us. Put his chair at the table anyway.",
  "Emily found the wedding tapes. The audio is terrible and it is the best thing I've watched all year.",
  "First snow at the cottage. The kids lasted eleven minutes outside and two hours by the fire.",
  "Rachel confirmed it: the Wright line goes back to a farm in Yorkshire, 1790. Four hundred years of stubborn people, verified.",
  "Made Grandma's shortbread from the card in her own handwriting. Slightly burnt. Still correct.",
  "Uncle David restored the rocking chair. Same wood, same joints, seventy years later.",
  "Noah's team won. He talked about it for the entire drive home, and then again at dinner.",
  "Beach day. Nobody checked a phone for four hours, which may be a family record.",
  "The last photo of all four generations together. Taken two months before we lost her.",
  "Cleaning out the attic turned into three hours of sitting on the floor reading letters.",
];

function buildJohnsonMemories(): Memory[] {
  const out: Memory[] = [];
  for (let i = 0; i < 42; i += 1) {
    const authorId = johnsonAuthors[i % johnsonAuthors.length]!;
    const text = memoryTexts[i % memoryTexts.length]!;
    const photoCount = [1, 0, 3, 2, 1, 4, 1, 6, 2, 0][i % 10]!;
    const photos = Array.from({ length: photoCount }, (_, k) =>
      P(photoPool[(i * 3 + k) % photoPool.length]!, 1000),
    );
    const days = Math.round(i * 24.5) + (i % 5);
    const commenters = ["u_margaret", "u_susan", "u_rachel", "u_emily", "u_david"];
    const commentCount = i % 4;
    out.push({
      id: `mem_${i + 1}`,
      familyId: "fam_johnson",
      authorId,
      text,
      photos,
      createdAt: ago(days, i % 12),
      reactions: {
        heart: 3 + ((i * 7) % 22),
        joy: (i * 5) % 14,
        sad: i % 9 === 0 ? 4 : 0,
        wow: (i * 3) % 8,
      },
      myReaction: i % 6 === 0 ? "heart" : null,
      comments: Array.from({ length: commentCount }, (_, k) => ({
        id: `mem_${i + 1}_c${k}`,
        authorId: commenters[(i + k) % commenters.length]!,
        text: [
          "Oh, I remember this day so clearly.",
          "Please tell me someone kept the original.",
          "That's Aunt Vivian on the left, I'd know that coat anywhere.",
          "Saving this one to the vault.",
          "This made my whole week.",
        ][(i + k) % 5]!,
        createdAt: ago(days, (i % 12) + k + 1),
      })),
      taggedUserIds: i % 3 === 0 ? ["u_helen", "u_margaret"] : [],
    });
  }
  return out;
}

const chenMemories: Memory[] = [
  {
    id: "cmem_1",
    familyId: "fam_chen",
    authorId: "c_daniel",
    text: "Fifty years since Dad opened the kitchen on Main Street. Same wok, different hands.",
    photos: [P(photoPool[2]!, 1000), P(photoPool[7]!, 1000)],
    createdAt: ago(4),
    reactions: { heart: 21, joy: 6, sad: 2, wow: 3 },
    myReaction: null,
    comments: [{ id: "cmem_1_c0", authorId: "c_lin", text: "He would be so proud of you.", createdAt: ago(3) }],
    taggedUserIds: ["c_wei"],
  },
  {
    id: "cmem_2",
    familyId: "fam_chen",
    authorId: "c_sophia",
    text: "Digitised the last album from the Guangzhou years. 412 photos, all restored.",
    photos: [P(photoPool[10]!, 1000)],
    createdAt: ago(12),
    reactions: { heart: 17, joy: 4, sad: 0, wow: 9 },
    myReaction: null,
    comments: [],
    taggedUserIds: [],
  },
  {
    id: "cmem_3",
    familyId: "fam_chen",
    authorId: "c_lin",
    text: "Lunar New Year, everyone home, nobody late for once.",
    photos: [P(photoPool[3]!, 1000), P(photoPool[5]!, 1000), P(photoPool[8]!, 1000)],
    createdAt: ago(31),
    reactions: { heart: 28, joy: 11, sad: 0, wow: 2 },
    myReaction: null,
    comments: [],
    taggedUserIds: [],
  },
];

export const memories: Memory[] = [...buildJohnsonMemories(), ...chenMemories];

/* ------------------------------------------------------------------ */
/* Albums & media                                                      */
/* ------------------------------------------------------------------ */

export const albums: Album[] = [
  { id: "alb_summer24", familyId: "fam_johnson", name: "Summer 2024", coverUrl: P(photoPool[1]!, 900), description: "Lake Simcoe, six weekends, one very tired dog.", year: 2024 },
  { id: "alb_reunion23", familyId: "fam_johnson", name: "Reunion 2023", coverUrl: P(photoPool[0]!, 900), description: "Forty-one Johnsons in one backyard.", year: 2023 },
  { id: "alb_holidays", familyId: "fam_johnson", name: "Holidays", coverUrl: P(photoPool[12]!, 900), description: "Every Christmas since 2015.", year: 2025 },
  { id: "alb_archive", familyId: "fam_johnson", name: "The Archive (1948–1989)", coverUrl: P(photoPool[9]!, 900), description: "Scanned slides, prints and negatives.", year: 1948 },
  { id: "alb_cottage", familyId: "fam_johnson", name: "Cottage Chaos", coverUrl: P(photoPool[19]!, 900), description: "Curated by Olivia, age 15.", year: 2025 },
  { id: "alb_chen_ny", familyId: "fam_chen", name: "Lunar New Year", coverUrl: P(photoPool[3]!, 900), description: "Twelve years of red envelopes.", year: 2026 },
];

const captions = [
  "The whole table, before the plates arrived",
  "Grandpa's hands, still steady",
  "Dock at golden hour",
  "First swim of the season",
  "Three generations, one bad haircut",
  "The kitchen at midnight",
  "Backyard, reunion Saturday",
  "Olivia and the cello",
  "Snow on the cottage roof",
  "Letters, found in the attic",
];

export const mediaItems: MediaItem[] = albums.flatMap((album, ai) =>
  Array.from({ length: album.id === "alb_chen_ny" ? 6 : 6 }, (_, i) => ({
    id: `media_${album.id}_${i}`,
    familyId: album.familyId,
    albumId: album.id,
    url: P(photoPool[(ai * 5 + i * 2) % photoPool.length]!, 1200),
    caption: captions[(ai + i) % captions.length]!,
    takenAt: ago(30 * ai + i * 3),
    uploadedBy: johnsonAuthors[(ai + i) % johnsonAuthors.length]!,
    likes: 3 + ((ai * 7 + i * 5) % 26),
  })),
);

/* ------------------------------------------------------------------ */
/* Events                                                              */
/* ------------------------------------------------------------------ */

export const events: FamilyEvent[] = [
  {
    id: "ev_reunion26",
    familyId: "fam_johnson",
    title: "Johnson Family Reunion 2026",
    type: "reunion",
    date: "2026-08-15",
    time: "12:00",
    location: "Lake Simcoe Cottage, Ontario",
    description:
      "The big one. Four generations, three barbecues and the annual and highly contested horseshoe tournament. Bring a dish and a story.",
    coverPhotoUrl: P(photoPool[0]!, 1600),
    attendees: ["u_john", "u_emily", "u_margaret", "u_peter", "u_david", "u_susan", "u_olivia", "u_noah"],
    maybe: ["u_michael", "u_rachel"],
    photos: [],
    comments: [
      { id: "ev1c1", authorId: "u_susan", text: "I'm bringing the paella pan. Again.", createdAt: ago(6) },
      { id: "ev1c2", authorId: "u_michael", text: "Trying to move a survey week. Fingers crossed.", createdAt: ago(4) },
    ],
  },
  { id: "ev_bd_olivia", familyId: "fam_johnson", title: "Olivia turns 16", type: "birthday", date: "2026-09-12", time: "17:00", location: "Toronto, ON", description: "Cake, cello, and absolutely no speeches (her rule).", coverPhotoUrl: P(photoPool[4]!, 1600), attendees: ["u_john", "u_emily", "u_noah", "u_margaret"], maybe: ["u_rachel"], photos: [], comments: [] },
  { id: "ev_anniv_mp", familyId: "fam_johnson", title: "Margaret & Peter — 47 years", type: "anniversary", date: "2026-09-22", location: "Toronto, ON", description: "Dinner at the same restaurant as always.", coverPhotoUrl: P(photoPool[11]!, 1600), attendees: ["u_margaret", "u_peter", "u_john"], maybe: [], photos: [], comments: [] },
  { id: "ev_bd_noah", familyId: "fam_johnson", title: "Noah turns 13", type: "birthday", date: "2027-03-28", location: "Toronto, ON", description: "Hockey party. Brace yourself.", coverPhotoUrl: P(photoPool[16]!, 1600), attendees: ["u_john", "u_emily", "u_olivia"], maybe: [], photos: [], comments: [] },
  { id: "ev_helen_mem", familyId: "fam_johnson", title: "Helen's Memorial Walk", type: "other", date: "2026-10-04", time: "10:00", location: "Withrow Park, Toronto", description: "The walk she took every morning for thirty years. We do it together once a year.", coverPhotoUrl: P(photoPool[13]!, 1600), attendees: ["u_margaret", "u_john", "u_emily", "u_rachel"], maybe: ["u_david"], photos: [], comments: [] },
  { id: "ev_thanks25", familyId: "fam_johnson", title: "Thanksgiving 2025", type: "other", date: "2025-10-13", location: "Barrie, ON", description: "Nineteen people, one oven, zero casualties.", coverPhotoUrl: P(photoPool[6]!, 1600), attendees: ["u_john", "u_emily", "u_david", "u_susan", "u_margaret", "u_peter"], maybe: [], photos: [P(photoPool[6]!, 1000), P(photoPool[7]!, 1000), P(photoPool[8]!, 1000)], comments: [] },
  { id: "ev_xmas25", familyId: "fam_johnson", title: "Christmas at the Thompsons", type: "other", date: "2025-12-25", location: "Toronto, ON", description: "Grandma's shortbread recipe, year eight without her.", coverPhotoUrl: P(photoPool[12]!, 1600), attendees: ["u_john", "u_emily", "u_olivia", "u_noah", "u_margaret", "u_peter"], maybe: [], photos: [P(photoPool[12]!, 1000), P(photoPool[14]!, 1000)], comments: [] },
  { id: "ev_bd_margaret", familyId: "fam_johnson", title: "Margaret turns 71", type: "birthday", date: "2026-05-19", location: "Toronto, ON", description: "Garden lunch.", coverPhotoUrl: P(photoPool[2]!, 1600), attendees: ["u_john", "u_emily", "u_david"], maybe: [], photos: [P(photoPool[2]!, 1000)], comments: [] },
  { id: "ev_cottage_open", familyId: "fam_johnson", title: "Cottage Opening Weekend", type: "other", date: "2026-05-23", location: "Lake Simcoe, ON", description: "Docks in, shutters off, first coffee on the porch.", coverPhotoUrl: P(photoPool[9]!, 1600), attendees: ["u_john", "u_david", "u_noah"], maybe: [], photos: [P(photoPool[9]!, 1000)], comments: [] },
  { id: "ev_bd_david", familyId: "fam_johnson", title: "David turns 68", type: "birthday", date: "2026-09-30", location: "Barrie, ON", description: "Workshop open house.", coverPhotoUrl: P(photoPool[15]!, 1600), attendees: ["u_susan", "u_michael", "u_rachel"], maybe: ["u_john"], photos: [], comments: [] },
  { id: "ev_bd_emily", familyId: "fam_johnson", title: "Emily turns 44", type: "birthday", date: "2026-11-03", location: "Toronto, ON", description: "Studio dinner.", coverPhotoUrl: P(photoPool[17]!, 1600), attendees: ["u_john", "u_olivia", "u_noah"], maybe: [], photos: [], comments: [] },
  { id: "ev_anniv_ds", familyId: "fam_johnson", title: "David & Susan — 42 years", type: "anniversary", date: "2026-06-16", location: "Barrie, ON", description: "Quiet one, by request.", coverPhotoUrl: P(photoPool[18]!, 1600), attendees: ["u_david", "u_susan"], maybe: [], photos: [], comments: [] },
  { id: "ev_bd_john", familyId: "fam_johnson", title: "John turns 46", type: "birthday", date: "2026-06-24", location: "Toronto, ON", description: "Backyard, burgers, done by nine.", coverPhotoUrl: P(photoPool[1]!, 1600), attendees: ["u_emily", "u_olivia", "u_noah", "u_margaret"], maybe: [], photos: [P(photoPool[1]!, 1000)], comments: [] },
  { id: "ev_genealogy", familyId: "fam_johnson", title: "Genealogy Night (online)", type: "other", date: "2026-09-05", time: "20:00", location: "Video call", description: "Rachel presents the Yorkshire findings. Bring questions.", coverPhotoUrl: P(photoPool[10]!, 1600), attendees: ["u_rachel", "u_john", "u_margaret"], maybe: ["u_michael", "u_susan"], photos: [], comments: [] },
  { id: "ev_bd_ava", familyId: "fam_johnson", title: "Ava turns 10", type: "birthday", date: "2026-12-01", location: "Montréal, QC", description: "Double digits.", coverPhotoUrl: P(photoPool[19]!, 1600), attendees: ["u_rachel"], maybe: ["u_john"], photos: [], comments: [] },
  { id: "ev_chen_ny", familyId: "fam_chen", title: "Lunar New Year Dinner", type: "other", date: "2027-02-06", location: "Vancouver, BC", description: "Chen's Kitchen, closed to the public, open to everyone else.", coverPhotoUrl: P(photoPool[3]!, 1600), attendees: ["c_lin", "c_daniel", "c_grace", "c_sophia"], maybe: ["c_mei"], photos: [], comments: [] },
];

/* ------------------------------------------------------------------ */
/* Legacy vault                                                        */
/* ------------------------------------------------------------------ */

export const vaultItems: VaultItem[] = [
  { id: "v1", familyId: "fam_johnson", title: "Message to My Grandchildren", kind: "message", authorId: "u_margaret", sealedAt: ago(420), unlock: { kind: "date", date: "2035-01-01" }, recipients: ["u_olivia", "u_noah", "u_ava"], preview: "Sealed letter, 1,240 words", sizeLabel: "4 KB" },
  { id: "v2", familyId: "fam_johnson", title: "My Life Lessons", kind: "letter", authorId: "u_peter", sealedAt: ago(300), unlock: { kind: "passing" }, recipients: ["u_john", "u_olivia", "u_noah"], preview: "Handwritten, scanned in 12 pages", sizeLabel: "18 MB" },
  { id: "v3", familyId: "fam_johnson", title: "Family History Video — The Cottage Years", kind: "video", authorId: "u_john", sealedAt: ago(210), unlock: { kind: "date", date: "2030-12-25" }, recipients: ["u_olivia", "u_noah", "u_ava"], preview: "48 min, restored 8mm and interviews", sizeLabel: "3.1 GB" },
  { id: "v4", familyId: "fam_johnson", title: "Grandma Helen's Recorded Stories", kind: "audio", authorId: "u_helen", sealedAt: ago(2800), unlock: { kind: "date", date: "2028-04-10" }, recipients: ["u_margaret", "u_john", "u_rachel"], preview: "14 h 22 min across 31 tapes", sizeLabel: "2.4 GB" },
  { id: "v5", familyId: "fam_johnson", title: "For Olivia, on Her Wedding Day", kind: "letter", authorId: "u_emily", sealedAt: ago(180), unlock: { kind: "age", age: 25 }, recipients: ["u_olivia"], preview: "Sealed letter, 890 words", sizeLabel: "3 KB" },
  { id: "v6", familyId: "fam_johnson", title: "The Workshop — How Everything Was Built", kind: "video", authorId: "u_david", sealedAt: ago(150), unlock: { kind: "date", date: "2032-06-01" }, recipients: ["u_noah", "u_michael"], preview: "6 lessons, 2 h 10 min", sizeLabel: "1.7 GB" },
  { id: "v7", familyId: "fam_johnson", title: "What I Never Told You About 1974", kind: "message", authorId: "u_margaret", sealedAt: ago(95), unlock: { kind: "passing" }, recipients: ["u_john"], preview: "Sealed message", sizeLabel: "2 KB" },
  { id: "v8", familyId: "fam_johnson", title: "Robert's War Letters (transcribed)", kind: "letter", authorId: "u_robert", sealedAt: ago(3200), unlock: { kind: "date", date: "2027-11-22" }, recipients: ["u_john", "u_rachel", "u_michael"], preview: "63 letters, 1943–1946", sizeLabel: "46 MB" },
  { id: "v9", familyId: "fam_johnson", title: "A Song for Ava", kind: "audio", authorId: "u_rachel", sealedAt: ago(60), unlock: { kind: "date", date: "2034-12-01" }, recipients: ["u_ava"], preview: "3 min 41 s, recorded at home", sizeLabel: "9 MB" },
  { id: "v10", familyId: "fam_johnson", title: "Instructions for the Cottage", kind: "message", authorId: "u_john", sealedAt: ago(30), unlock: { kind: "passing" }, recipients: ["u_olivia", "u_noah"], preview: "Practical, unsentimental, mostly about the pump", sizeLabel: "6 KB" },
  { id: "v11", familyId: "fam_chen", title: "Recipes in My Own Hand", kind: "letter", authorId: "c_lin", sealedAt: ago(240), unlock: { kind: "date", date: "2029-02-06" }, recipients: ["c_sophia", "c_mei"], preview: "38 scanned recipe cards", sizeLabel: "62 MB" },
  { id: "v12", familyId: "fam_chen", title: "Grandpa Wei's Last Tapes", kind: "audio", authorId: "c_lucas", sealedAt: ago(120), unlock: { kind: "passing" }, recipients: ["c_daniel", "c_grace"], preview: "Restored cassettes, 9 h", sizeLabel: "1.2 GB" },
];

/* ------------------------------------------------------------------ */
/* Messages                                                            */
/* ------------------------------------------------------------------ */

export const chats: Chat[] = [
  { id: "chat_family", familyId: "fam_johnson", name: "Johnson Family Chat", kind: "group", participantIds: ["u_john", "u_emily", "u_margaret", "u_peter", "u_david", "u_susan", "u_rachel", "u_michael"], avatarUrl: P(photoPool[0]!, 200) },
  { id: "chat_reunion", familyId: "fam_johnson", name: "Reunion 2026 Planning", kind: "group", participantIds: ["u_john", "u_margaret", "u_susan", "u_rachel"], avatarUrl: P(photoPool[6]!, 200) },
  { id: "chat_margaret", familyId: "fam_johnson", name: "Margaret Johnson-Thompson", kind: "direct", participantIds: ["u_john", "u_margaret"] },
  { id: "chat_emily", familyId: "fam_johnson", name: "Emily Thompson", kind: "direct", participantIds: ["u_john", "u_emily"] },
  { id: "chat_rachel", familyId: "fam_johnson", name: "Rachel Johnson-Lee", kind: "direct", participantIds: ["u_john", "u_rachel"] },
  { id: "chat_chen", familyId: "fam_chen", name: "Chen Family Chat", kind: "group", participantIds: ["c_daniel", "c_lin", "c_grace", "c_sophia", "c_lucas"], avatarUrl: P(photoPool[3]!, 200) },
];

const familyChatLines: Array<[string, string]> = [
  ["u_margaret", "Has anyone seen the blue photo album from the cottage? The one with the metal corners."],
  ["u_john", "It's in the archive box in my office. I scanned it last month — it's all in the gallery now."],
  ["u_margaret", "You scanned all of it? John."],
  ["u_john", "All 240 pages. Album is called 'The Archive (1948–1989)'."],
  ["u_susan", "This is why we made you admin."],
  ["u_david", "Speaking of the cottage — the dock needs two new boards before August."],
  ["u_john", "Noted. I'll bring the cedar up on the 15th."],
  ["u_rachel", "Unrelated but important: I found the 1790 Yorkshire record. It's real."],
  ["u_margaret", "Rachel!!"],
  ["u_rachel", "Presenting everything on genealogy night. Bring wine."],
  ["u_emily", "I'll photograph the documents properly so they go in the archive at full resolution."],
  ["u_michael", "Trying to shift a survey week so I can actually make the reunion this year."],
  ["u_susan", "It has been four years, Michael."],
  ["u_michael", "I am aware, Susan."],
  ["u_peter", "Potato salad is handled. Do not assign anyone else."],
  ["u_margaret", "Peter has spoken."],
  ["u_olivia", "can i bring a friend to the reunion"],
  ["u_john", "Yes. Tell her about the horseshoe tournament in advance."],
  ["u_emily", "Reminder that the vault video needs everyone's interview clip by October."],
  ["u_david", "Mine's recorded. Twenty minutes, mostly about wood."],
  ["u_john", "Perfect. That's exactly what it should be."],
  ["u_margaret", "Sealed my letter to the grandchildren today. Unlocks 2035. Don't ask."],
];

export const chatMessages: ChatMessage[] = [
  ...familyChatLines.map(([authorId, text], i) => ({
    id: `msg_f_${i}`,
    chatId: "chat_family",
    authorId,
    text,
    createdAt: ago(3, 22 - i),
  })),
  ...[
    ["u_margaret", "Are you bringing the cedar boards up on the 15th?"],
    ["u_john", "Already in the truck."],
    ["u_margaret", "You're a good son. Mostly."],
  ].map(([authorId, text], i) => ({ id: `msg_m_${i}`, chatId: "chat_margaret", authorId: authorId!, text: text!, createdAt: ago(1, 6 - i) })),
  ...[
    ["u_emily", "Did you upload the recital video?"],
    ["u_john", "Uploading now. It's 4K, give it a minute."],
    ["u_emily", "Olivia wants it in the vault, not the feed."],
    ["u_john", "Vault it is."],
  ].map(([authorId, text], i) => ({ id: `msg_e_${i}`, chatId: "chat_emily", authorId: authorId!, text: text!, createdAt: ago(0, 9 - i) })),
  ...[
    ["u_rachel", "Sending you the Yorkshire scans tonight."],
    ["u_john", "Put them straight in the archive album."],
  ].map(([authorId, text], i) => ({ id: `msg_r_${i}`, chatId: "chat_rachel", authorId: authorId!, text: text!, createdAt: ago(2, 4 - i) })),
  ...[
    ["u_susan", "Menu draft is in the shared note."],
    ["u_john", "Approved, obviously."],
    ["u_rachel", "Adding a genealogy table by the porch."],
  ].map(([authorId, text], i) => ({ id: `msg_p_${i}`, chatId: "chat_reunion", authorId: authorId!, text: text!, createdAt: ago(5, 8 - i) })),
  ...[
    ["c_daniel", "Booking the restaurant for February."],
    ["c_lin", "Order the good tea this time."],
  ].map(([authorId, text], i) => ({ id: `msg_c_${i}`, chatId: "chat_chen", authorId: authorId!, text: text!, createdAt: ago(2, 5 - i) })),
];

/* ------------------------------------------------------------------ */
/* Forums                                                              */
/* ------------------------------------------------------------------ */

export const forumCategories: ForumCategory[] = [
  { id: "cat_recipes", familyId: "fam_johnson", name: "Family Recipes", description: "Handwritten cards, disputed measurements, sacred rules.", icon: "utensils" },
  { id: "cat_traditions", familyId: "fam_johnson", name: "Family Traditions", description: "Why we do the things we do, and who started them.", icon: "sparkles" },
  { id: "cat_genealogy", familyId: "fam_johnson", name: "Genealogy Research", description: "Records, dead ends and breakthroughs.", icon: "search" },
  { id: "cat_elders", familyId: "fam_johnson", name: "Advice from Elders", description: "Ask anything. Someone here has already lived it.", icon: "heart" },
  { id: "cat_chen_food", familyId: "fam_chen", name: "Chen's Kitchen", description: "Fifty years of restaurant recipes.", icon: "utensils" },
];

const threadSeed: Array<[string, string, string, string[]]> = [
  ["cat_recipes", "Grandma Helen's shortbread — the real ratio", "u_susan", ["The card says '3 parts flour', but she never used a scale in her life. I weighed what was left in her tin: it's 3:2:1 by weight.", "I've made it four times with 3:2:1 and it's right. It's finally right.", "Adding this to the recipe section so it stops living in a text thread."]],
  ["cat_recipes", "The tourtière argument, settled", "u_margaret", ["Cinnamon or no cinnamon. Dad said no. Mum did it anyway, quietly, for thirty years.", "So the answer is: cinnamon, secretly."]],
  ["cat_traditions", "Why we set an empty chair at Christmas", "u_john", ["Started in 2003, the first Christmas without Dad. Nobody decided it — it just happened and never stopped.", "Ava asked about it this year. I told her it's for whoever isn't here yet, and whoever isn't here anymore."]],
  ["cat_traditions", "The horseshoe tournament rules (official)", "u_david", ["Posting these so we stop relitigating them every August.", "Rule 4 remains contested and I'm fine with that."]],
  ["cat_genealogy", "1790 Yorkshire record — confirmed", "u_rachel", ["Parish register, Kirkby Malzeard. Thomas Wright, farm labourer. It's the line.", "Scans are in the archive album at full resolution.", "This pushes us back four generations further than we had."]],
  ["cat_genealogy", "Who is the woman in the 1961 cottage photo?", "u_michael", ["Left of Grandpa, dark coat, holding a child.", "My guess is Aunt Vivian, Helen's sister, but the dates are tight.", "Vivian was in Halifax in 1961 — I have a letter postmarked that July. So it isn't her."]],
  ["cat_elders", "How do you keep a marriage going for 47 years?", "u_olivia", ["School project, but also I actually want to know.", "Separate reading lamps. I'm not joking.", "You decide once, and then you keep deciding. That's the whole trick."]],
  ["cat_elders", "What should we be recording before it's too late?", "u_emily", ["Voices. Not photos — we have thousands of photos. We have almost no recordings of how people sounded.", "Agreed. Grandma's tapes are the single most valuable thing in this archive.", "Starting a list of who to interview at the reunion."]],
  ["cat_chen_food", "Dad's wok seasoning method", "c_daniel", ["Writing it down before it's lost. Three passes, always.", "This should be in the vault too."]],
];

export const forumThreads: ForumThread[] = threadSeed.map(([categoryId, title, authorId, bodies], i) => {
  const cat = forumCategories.find((c) => c.id === categoryId)!;
  const responders = ["u_margaret", "u_john", "u_rachel", "u_david", "u_susan"];
  return {
    id: `thr_${i + 1}`,
    categoryId,
    familyId: cat.familyId,
    title,
    authorId,
    createdAt: ago(9 + i * 7),
    posts: bodies.map((body, k) => ({
      id: `thr_${i + 1}_p${k}`,
      authorId: k === 0 ? authorId : responders[(i + k) % responders.length]!,
      body,
      createdAt: ago(9 + i * 7, -k * 5),
    })),
  };
});

/* ------------------------------------------------------------------ */
/* Recipes                                                             */
/* ------------------------------------------------------------------ */

export const recipes: Recipe[] = [
  {
    id: "rec_shortbread",
    familyId: "fam_johnson",
    title: "Helen's Christmas Shortbread",
    authorId: "u_helen",
    originStory:
      "Written on an index card in 1962 and never revised. The corner is burnt because Helen used it as a coaster for a hot tin, which she always denied.",
    photoUrl: P(photoPool[12]!, 1000),
    servings: 24,
    minutes: 50,
    ingredients: ["300 g plain flour", "200 g cold butter", "100 g caster sugar", "Pinch of salt", "1 tsp vanilla"],
    steps: ["Rub the butter into the flour until it looks like sand.", "Add sugar, salt and vanilla; bring together without kneading.", "Press into a tin, prick all over, chill 30 minutes.", "Bake at 160 °C for 35–40 minutes until barely golden.", "Cut while warm. Cool in the tin."],
  },
  {
    id: "rec_tourtiere",
    familyId: "fam_johnson",
    title: "The Contested Tourtière",
    authorId: "u_margaret",
    originStory: "Robert insisted there was no cinnamon in it. There was always cinnamon in it.",
    photoUrl: P(photoPool[5]!, 1000),
    servings: 8,
    minutes: 105,
    ingredients: ["700 g minced pork", "1 onion, finely diced", "2 cloves garlic", "1 potato, grated", "½ tsp cinnamon (secretly)", "Double pastry crust"],
    steps: ["Brown the pork with onion and garlic.", "Add grated potato and 200 ml stock; simmer 25 minutes.", "Season, cool completely.", "Fill the crust, seal, vent.", "Bake 45 minutes at 190 °C."],
  },
  {
    id: "rec_pancakes",
    familyId: "fam_johnson",
    title: "Grandpa Robert's Too-Much-Cinnamon Pancakes",
    authorId: "u_robert",
    originStory: "Saturday mornings at the cottage, 1961 to 2003. The measurement was 'until it looks wrong'.",
    photoUrl: P(photoPool[14]!, 1000),
    servings: 4,
    minutes: 25,
    ingredients: ["250 g flour", "2 eggs", "350 ml buttermilk", "2 tsp baking powder", "1½ tsp cinnamon", "Butter, generously"],
    steps: ["Whisk dry ingredients.", "Add eggs and buttermilk; leave lumps alone.", "Rest 10 minutes.", "Fry in butter until deeply golden.", "Serve immediately, never stacked."],
  },
  {
    id: "rec_paella",
    familyId: "fam_johnson",
    title: "Susan's Reunion Paella",
    authorId: "u_susan",
    originStory: "Brought from Madrid in 1984 and scaled up every year until it needed its own pan and its own table.",
    photoUrl: P(photoPool[6]!, 1000),
    servings: 20,
    minutes: 90,
    ingredients: ["1.2 kg bomba rice", "3 l stock", "Saffron", "Chicken thighs", "Prawns", "Green beans, butter beans", "Smoked paprika"],
    steps: ["Sear the chicken; set aside.", "Soffrito with tomato and paprika.", "Rice in, stock in, saffron in. Do not stir again.", "Prawns on top for the last 8 minutes.", "Rest under a towel for 10 minutes."],
  },
  {
    id: "rec_bread",
    familyId: "fam_johnson",
    title: "Cottage Morning Bread",
    authorId: "u_john",
    originStory: "Started as a way to use up the sourdough starter Olivia named 'Gerald'.",
    photoUrl: P(photoPool[9]!, 1000),
    servings: 1,
    minutes: 900,
    ingredients: ["500 g strong flour", "350 g water", "100 g starter", "10 g salt"],
    steps: ["Mix, rest 45 minutes.", "Four folds over two hours.", "Shape, cold prove overnight.", "Bake in a covered pot at 240 °C, 20 minutes lid on, 20 off."],
  },
  {
    id: "rec_chen_noodles",
    familyId: "fam_chen",
    title: "Chen's Kitchen Birthday Noodles",
    authorId: "c_lin",
    originStory: "Served at every family birthday since 1972. Never cut the noodles — it's bad luck and Lin will notice.",
    photoUrl: P(photoPool[7]!, 1000),
    servings: 6,
    minutes: 40,
    ingredients: ["Fresh long noodles", "Ginger", "Spring onion", "Light soy", "Sesame oil", "Chicken stock"],
    steps: ["Infuse the stock with ginger and spring onion.", "Cook noodles just under.", "Finish in the broth 30 seconds.", "Sesame oil off the heat. Serve whole."],
  },
];

/* ------------------------------------------------------------------ */
/* Notifications                                                       */
/* ------------------------------------------------------------------ */

export const notifications: AppNotification[] = [
  { id: "n1", actorId: "u_rachel", text: "confirmed the 1790 Yorkshire record in Genealogy Research", createdAt: ago(0, 2), read: false },
  { id: "n2", actorId: "u_emily", text: "added 24 photos to Cottage Chaos", createdAt: ago(0, 5), read: false },
  { id: "n3", actorId: "u_margaret", text: "sealed a new vault item: Message to My Grandchildren", createdAt: ago(1, 3), read: false },
  { id: "n4", actorId: "u_david", text: "commented on your memory about the carpentry sign", createdAt: ago(1, 9), read: false },
  { id: "n5", actorId: "u_susan", text: "is going to Johnson Family Reunion 2026", createdAt: ago(2), read: true },
  { id: "n6", actorId: "u_olivia", text: "shared a memory: the cello recital", createdAt: ago(3), read: true },
  { id: "n7", actorId: "u_michael", text: "replied in Who is the woman in the 1961 cottage photo?", createdAt: ago(4), read: true },
  { id: "n8", actorId: "u_peter", text: "claimed potato salad duty. Again.", createdAt: ago(5), read: true },
];

export const CURRENT_USER_ID = "u_john";

export const byId = <T extends { id: string }>(list: T[], id: string): T | undefined =>
  list.find((item) => item.id === id);

export const userById = (id: string): User =>
  users.find((usr) => usr.id === id) ?? users[6]!;
